repositoryUrl: https://github.com/dynamsoft-docs/label-recognition-docs-server/blob/main
repository: Dynamsoft-docs/label-recognition-docs-server
docFullPath: https://www.dynamsoft.com/label-recognition/docs/server
firstLevelUrl: /label-recognition/docs/server
docHomePage: /label-recognition/docs/core/introduction/
needSearchIndex: true
searchNeedFilter: true



dlr_dotnet_api: /label-recognition/docs/server/programming/dotnet/api-reference/

dlr_java_api: /label-recognition/docs/server/programming/java/api-reference/

dlr_python_api: /label-recognition/docs/server/programming/python/api-reference/

dcvb_parameters_reference: /capture-vision/docs/core/parameters/reference/

dcvb_cpp_api: /capture-vision/docs/server/programming/cplusplus/api-reference/
dcvb_dotnet_api: /capture-vision/docs/server/programming/dotnet/api-reference/
dcvb_python_api: /capture-vision/docs/server/programming/python/api-reference/
dcvb_java_api: /capture-vision/docs/server/programming/java/api-reference/

assets: /label-recognition/docs/server/assets/
edit_icon: /label-recognition/docs/server/assets/img-icon/edit-icon.png
smile_icon: /label-recognition/docs/server/assets/img-icon/icon-smile.png
sad_icon: /label-recognition/docs/server/assets/img-icon/icon-sad.png
dbr_icon: /label-recognition/docs/server/server/assets/img-icon/icon-dbr.svg
dwt_icon: /label-recognition/docs/assets/img-icon/icon-dwt.svg
dnt_icon: /label-recognition/docs/server/assets/img-icon/icon-dnt.svg

useVersionTree: false
isDCV: true
useJSVersionV3: true

baseurl: "/label-recognition/docs/server"

plugins:
  - jemoji
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag


defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root

