useGroupedVersion: true

version_info_list:
  - value: latest version
  - value: 3.x
    child: 
      - 3.2.20_cplusplus
      - 3.2.10_cplusplus
      - 3.2.0_cplusplus
      - 3.0.30_cplusplus
      - 3.0.20_cplusplus
      - 3.0.10_cplusplus
      - 3.0.0_cplusplus
  - value: 2.x
    child:
      - 2.2.20_cplusplus
      - 2.2.11_cplusplus
      - 2.2.10_cplusplus
      - 2.2.0_cplusplus
      - 2.0.0_cplusplus
      - 2.2.20_c
      - 2.2.11_c
      - 2.2.10_c
      - 2.2.0_c
      - 2.0.0_c
      - 2.0.0_dotnet
      - 2.0.0_java
  - value: 1.x
    child:
      - 1.2.1_cplusplus
      - 1.2_cplusplus
      - 1.0_cplusplus
      - 1.2.1_c
      - 1.2_c
      - 1.0_c
      - 1.2.1_dotnet
      - 1.2_dotnet
      - 1.0_dotnet
      - 1.2.1_java
